# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sergio Orozco Torres
email: scot3004@gmail.com
lang: es_CO
locale: es
description: Sitio de presentación de Sergio Carlos Orozco Torres - Desarrollador web
subject: Presentación de Sergio Orozco Torres como desarrolador web
nombre: Sergio C. Orozco Torres
lema: Solo quien se esfuerza logra sus objetivos
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scot3004.secorto.com" # the base hostname & protocol for your site

author:
  name             : "Sergio C. Orozco Torres"
  avatar           : "/img/logo.png"
  bio              : "Especialista en seguridad informática, Automatizador PSL"
  location         : "Medellín, CO"
  email            :
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          : scot3004
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : scot3004
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : scot3004
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            : scot3004
  tumblr           :
  twitter          : scot3004
  vine             :
  weibo            :
  xing             :
  youtube          :
twitter:
  username: scot3004
facebook:
  app_id: '291685517914169'
  publisher: 'scot3004.secorto'
  admins: 'scot3004'
logo: '/img/logo.png'
social:
  links:
    - https://twitter.com/scot3004
    - https://www.facebook.com/scot3004
    - https://www.linkedin.com/in/scot3004
    - https://plus.google.com/+SergioOrozcoTorres
    - https://github.com/scot3004
    - https://codepen.io/scot3004
github_username: scot3004
license: AGPL-3.0

disqus: scot3004
comments: true

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "resources"
  - "nbproject"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gulpfile.js"
  - "Rakefile"
  - "config.rb"
  - "package.json"
  - "fontify.json"
  - "faviconDescription.json"
  - "npm-debug.log"
  - "CNAME"
  - "app.js"
  - "yarn.lock"
  - "README.md"
  - vendor
plugins:
  - 'jekyll-github-metadata'
  - 'jekyll-seo-tag'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "single"
      comments: true
      author_profile: true
      read_time: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portafolio
    values:
      layout: single
      author_profile: false
      share: true

tag_title_prefix: ''
tag_title_suffix: ' - posts etiquetados'

timezone: '-0500'

collections:
  portafolio:
    output: true

timeline-img: "/img/timeline/default.png"

# Analytics
analytics:
  provider: google-universal # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-10920504-3

repository: Scot3004/Scot3004.github.io

words_per_minute: 200

compress_html:
  ignore:
    envs: development

locale: "es-ES"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

include: ['_pages']

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
